### ISSUE TITLE
Forcibly setting $DISPLAY to :0

### ISSUE THREAD

**Issue by ViktorWalter** [klaxalk/linux-setup#121]
On
https://github.com/klaxalk/linux-setup/blob/ae0e32a5f1b87c5be01e51a99cf29703aab89049/appconfig/shell/commons.sh_git#L5
the `commons.sh` is setting the `$DISPLAY` variable to `:0`, in order to fix the keyboard repeat rate.
This is problematic, since it breaks ssh X11 Forwarding - when you do e.g. `ssh -X user@host`, the `sshd` on `host` sets `$DISPLAY` to the appropriate value corresponding to the remote display assigned to the remote session, e.g. `localhost:10.0`.
Sourcing `commons.sh` in my `.bashrc` / `.zshrc` sets it back to `:0`, so if I don't manually set it back I can't display remote graphical interfaces.
Instead of manually setting the variable, I would recommend to instead check *if* `$DISPLAY` is set before doing `xset r rate ...`.

**Comment by matemat13** [comment]
Maybe the best solution would be to save the original value of `$DISPLAY` and then set it back after this line? A good catch, nevertheless!

**Comment by ViktorWalter** [comment]
Yeah, that's my current workaround. But apparently we have linux-setup on drones and I'm told some people have already had trouble with `ssh -X` on them.

**Comment by klaxalk** [comment]
I am not even sure if the export needs to be there...

**Comment by klaxalk** [comment]
It seems it works even without it. I will remove it and let's observe if it breaks something.

**Comment by ViktorWalter** [comment]
This is the best attitude to have 😄.

**Comment by klaxalk** [comment]
Improvement by reduction :-).

**Comment by ViktorWalter** [comment]
Let's consider this solved until it breaks something then.
