### ISSUE TITLE
VIM mode incomplete

### ISSUE THREAD

**Issue by ViktorWalter** [klaxalk/linux-setup#3]
In the VIM mode, "inner" modifier does not work;
Steps to reproduce:
- F2 for VIM mode;
- move to the middle of a word;
- press: viw
      - expected behaviour: whole word is selected;
      - actual behaviour: selection from cursor position to the first letter of the next word (included)

**Comment by klaxalk** [comment]
This looks like a limited capability of tmux's vim mode... it probably can't do all the things vim can do...
