### ISSUE TITLE
Absolute path to submodule

### ISSUE THREAD

**Issue by spurnvoj** [klaxalk/linux-setup#5]
in dotbashrc the line with path ~/git/linux-setup/submodules/tmuxinator/completion/tmuxinator should be relative.

**Comment by spurnvoj** [comment]
In "/appconfig/tmux/dottmux" the path on line 161 should be relative.

**Comment by klaxalk** [comment]
Should be fixed. It it though necessary to remove the line source ***/dotbashrc from .brashrc and call the install.sh again.
