### ISSUE TITLE
The i3status bar freezes from time to time

### ISSUE THREAD

**Issue by matemat13** [klaxalk/linux-setup#52]
Title is self-explanatory...
This issue might be related to https://github.com/i3/i3/issues/3242

Possible solution: Use different status bar? Rollback to a more stable version?

**Comment by matemat13** [comment]
It seems that this issue is related to the `detacher.sh` script. After disabling any elements of the i3status bar, which use this script, the bar no longer freezes even after sleep and wake-up.

**Comment by spurnvoj** [comment]
It was happening to me often but it stopped after some updates... So I think that issue is solved :)

**Comment by matemat13** [comment]
I believe the fix was removing the scripts, which used detacher.sh, from the statusbar. There might be something about detacher that the statusbar dislikes.
