### ISSUE TITLE
Typo in README.md

### ISSUE THREAD

**Issue by matemat13** [klaxalk/linux-setup#6]
When copypasting commands from the readme the second line has an extra
`echo "`
which may confuse someone as the terminal will expect end of the quotes...

**Comment by matemat13** [comment]
I see now that the
`echo "`
probably belongs to the beginning of the last line.

**Comment by klaxalk** [comment]
Yes, that is intended. By creating the run.sh script first and then executing it, I avoid one issue: If you would pass the commands directly to the terminal, any required input (e.g. password) would be filled with the subsequent commands.
